---
- name: Undercloud configuration
  hosts: director
  gather_facts: no

  pre_tasks:
    - name: Wait for the undercloud to come up
      wait_for_connection:
        timeout: 60

    - name: Gathering facts
      setup:

  tasks:
    - name: Ensure stack user is set with the correct permissions
      import_tasks: tasks/02.01_stack_user.yml

    - name: Copy the key to login as stack user
      import_tasks: tasks/02.02_ssh_key.yml

  roles:
    - name: geerlingguy.swap
      swap_file_size_mb: '8192'
