- name: IMAGES - Unpack director images
  unarchive:
    src: "{{ item }}"
    dest: /home/stack/images/
    owner: stack
    group: stack
    remote_src: yes
  loop:
    - /usr/share/rhosp-director-images/overcloud-full-latest-16.2.tar
    - /usr/share/rhosp-director-images/ironic-python-agent-latest-16.2.tar
