- name: "LEAFS - Create directories for {{ leaf.name }}"
  file:
    path: "/home/stack/templates/{{ item }}"
    owner: stack
    group: stack
    state: directory
  loop:
    - "{{ leaf.name }}"
    - "{{ leaf.name }}/nic-configs"

- name: "TEMPLATES - Prepare templates for {{ leaf.name }}"
  template:
    src: "{{ item }}.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/{{ item }}"
    owner: stack
    group: stack
  loop:
    - instackenv.yaml
    - node-info.yaml
    - custom-overcloud.yaml
    - custom-network-configuration.yaml
    - custom-ceph.yaml

- name: "TEMPLATES - Prepare the nic-configs templates for {{ leaf.name }}"
  template:
    src: "nic-configs/nic-config.yaml.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/nic-configs/{{ item.profile }}.yaml"
    owner: stack
    group: stack
  when:
    - RHOSP_version < 17.0
    - roles_count[leaf.name][item.name] > 0
  loop: "{{ overcloud_roles }}"

- name: "TEMPLATES - RHOSP >= 17.0 nic-config files for {{ leaf.name }}"
  template:
    src: "templates/nic-configs/nic-config.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/nic-configs/{{ item.profile }}.j2"
    owner: stack
    group: stack
  when:
    - RHOSP_version >= 17.0
    - roles_count[leaf.name][item.name] > 0
  loop: "{{ overcloud_roles }}"

- name: SCRIPTS - Prepare the scripts
  template:
    src: "{{ item }}.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/{{ item }}"
    mode: "755"
    owner: stack
    group: stack
  loop:
    - pre_deployment.sh
    - deploy.sh