- name: "LEAFS - Create directories for {{ leaf.name }}"
  file:
    path: "/home/stack/templates/{{ leaf.name }}"
    owner: stack
    group: stack
    state: directory

- name: "TEMPLATES - Prepare templates for {{ leaf.name }}"
  template:
    src: "{{ item }}.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/{{ item }}"
    owner: stack
    group: stack
  loop:
    - instackenv.yaml
    - node-info.yaml
    - custom-overcloud.yaml
    - custom-network-configuration.yaml
    - custom-ceph.yaml
    - vip_data.yaml

- name: "TEMPLATES - Prepare roles_data.yaml depending on the version for {{ leaf.name }}"
  template:
    src: "roles_data_{{ RHOSP_version }}.yaml.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/roles_data.yaml"
    owner: stack
    group: stack

- name: SCRIPTS - Prepare the scripts
  template:
    src: "{{ item }}.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/{{ item }}"
    mode: "755"
    owner: stack
    group: stack
  loop:
    - pre_deployment.sh
    - deploy.sh