- name: "LEAFS - Create directories for {{ leaf.name }}"
  file:
    path: "/home/stack/templates/{{ item }}"
    owner: stack
    group: stack
    state: directory
  loop:
    - "{{ leaf.name }}"
    - "{{ leaf.name }}/nic-configs"

- name: "TEMPLATES - Prepare templates for {{ leaf.name }}"
  template:
    src: "{{ item }}.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/{{ item }}"
    owner: stack
    group: stack
  loop:
    - instackenv.yaml
    - node-info.yaml
    - custom-overcloud.yaml
    - network_data.yaml
    - custom-network-configuration.yaml
    - custom-ceph.yaml
    - vip_data.yaml

- name: "TEMPLATES - Prepare roles_data.yaml depending on the version for {{ leaf.name }}"
  template:
    src: "roles_data_{{ RHOSP_version }}.yaml.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/roles_data.yaml"
    owner: stack
    group: stack

- name: "TEMPLATES - Prepare the nic-configs templates for {{ leaf.name }}"
  template:
    src: "nic-configs/{{ item.nic_configs }}.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/nic-configs/{{ item.nic_configs }}"
    owner: stack
    group: stack
  loop: "{{ overcloud_roles }}"
  when: RHOSP_version != 17.0

- name: "TEMPLATES - RHOSP 17.0 nic-config files for {{ leaf.name }}"
  template:
    src: "templates/nic-configs/nic-config.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/nic-configs/{{ item.profile }}.j2"
    owner: stack
    group: stack
  loop: "{{ overcloud_roles }}"
  when: RHOSP_version == 17.0

- name: SCRIPTS - Prepare the scripts
  template:
    src: "{{ item }}.j2"
    dest: "/home/stack/templates/{{ leaf.name }}/{{ item }}"
    mode: "755"
    owner: stack
    group: stack
  loop:
    - pre_deployment.sh
    - deploy.sh