---
# tasks file for RHOSP-undercloud

- name: Verify the RHOSP version selected is supported
  fail:
    msg: "The selected RHOSP version ({{ RHOSP_version }}) is not supported by this role."
  when: RHOSP_version_supported[RHOSP_version] is not defined

- name: Configure swap file on the undercloud
  include_role:
    name: geerlingguy.swap
  vars:
    swap_file_size_mb: '8192'

- name: HOSTNAME - Change the hostname
  hostname:
    name: undercloud.localdomain

- name: Red Hat Subscription management
  import_tasks: tasks/subscription.yml

- name: REPOSITORIES - Enable the needed repositories only
  rhsm_repository:
    name: "{{ RHOSP_version_supported[RHOSP_version].repos }}"
    purge: yes

- name: MODULES - Enable and configure modules
  copy:
    dest: "/etc/dnf/modules.d/{{ item.name }}.module"
    content: |
      [{{ item.name }}]
      name={{ item.name }}
      stream={{ item.stream }}
      profiles={{ item.profiles }}
      state=enabled
  loop: "{{ RHOSP_version_supported[RHOSP_version].modules }}"

- name: PACKAGES - Install useful tools
  yum:
    name:
      - vim
      - wget
      - bash-completion 
    state: latest

- name: PACKAGES - Update all packages
  yum:
    name: '*'
    state: latest
  notify: HANDLER - Reboot the machine

- name: CONFIGFILES - Create directories
  file:
    path: "/home/stack/{{ item }}"
    owner: stack
    group: stack
    state: directory
  loop:
    - images
    - templates
    - templates/nic-configs

- name: CONFIGFILES - Set container images prepare file
  template:
    src: containers-prepare-parameter.yaml.j2
    dest: /home/stack/templates/containers-prepare-parameter.yaml
    owner: stack
    group: stack

- name: CONFIGFILES - Set custom undercloud parameters
  copy:
    src: templates/custom-undercloud-params.yaml
    dest: /home/stack/templates/custom-undercloud-params.yaml
    owner: stack
    group: stack

- name: CONFIGFILES - Set undercloud configuration file
  template:
    src: "undercloud.conf.j2"
    dest: "/home/stack/undercloud.conf"
    owner: stack
    group: stack

- name: PACKAGES - Install needed packages
  yum:
    name: "{{ RHOSP_version_supported[RHOSP_version].packages }}"
    state: latest

- name: IMAGES - Unpack director images
  unarchive:
    src: "{{ item }}"
    dest: /home/stack/images/
    owner: stack
    group: stack
    remote_src: yes
  loop:
    - "/usr/share/rhosp-director-images/overcloud-full-latest-{{ RHOSP_version }}.tar"
    - "/usr/share/rhosp-director-images/ironic-python-agent-latest-{{ RHOSP_version }}.tar"

- name: IMAGES - Download images for testing
  get_url:
    url: "{{ item.url }}"
    dest: "images/{{ item.name }}"
    owner: stack
    group: stack
    timeout: 30
  loop:
    - url: "{{ RHOSP_version_supported[RHOSP_version].rhel_image.url }}"
      name: "{{ RHOSP_version_supported[RHOSP_version].rhel_image.name }}"
    - url: https://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img
      name: cirros.qcow2
  retries: 3
  delay: 10
  register: result
  until: result is not failed

- name: TEMPLATES - Prepare nodes file
  template:
    src: instackenv.yaml.j2
    dest: /home/stack/templates/instackenv.yaml
    owner: stack
    group: stack

- name: TEMPLATES - Prepare node info file
  template:
    src: node-info.yaml.j2
    dest: /home/stack/templates/node-info.yaml
    owner: stack
    group: stack

- name: TEMPLATES - Prepare roles data file
  template:
    src: roles_data.yaml.j2
    dest: /home/stack/templates/roles_data.yaml
    owner: stack
    group: stack

- name: TEMPLATES - Perpare the custom overcloud parameters template
  template:
    src: custom-overcloud.yaml.j2
    dest: /home/stack/templates/custom-overcloud.yaml
    owner: stack
    group: stack

- name: TEMPLATES - Perpare the custom network data
  template:
    src: network_data.yaml.j2
    dest: /home/stack/templates/network_data.yaml
    owner: stack
    group: stack

- name: TEMPLATES - Perpare the custom network configuration template
  template:
    src: custom-network-configuration.yaml.j2
    dest: /home/stack/templates/custom-network-configuration.yaml
    owner: stack
    group: stack

- name: TEMPLATES - Prepare the nic-configs templates
  template:
    src: "nic-configs/{{ item.nic_configs }}.j2"
    dest: "/home/stack/templates/nic-configs/{{ item.nic_configs }}"
    owner: stack
    group: stack
  loop: "{{ overcloud_roles }}"

- name: POSTDEPLOYMENT - Prepare post-deployment script
  template:
    src: post_deployment.sh.j2
    dest: /home/stack/post_deployment.sh
    mode: '755'
    owner: stack
    group: stack
