---
# tasks file for RHOSP-undercloud

- name: Verify the RHOSP version selected is supported
  fail:
    msg: "The selected RHOSP version ({{ RHOSP_version }}) is not supported by this role."
  when: RHOSP_version_supported[RHOSP_version] is not defined

- name: Verify vms and physical profiles
  import_tasks: tasks/profiles.yml

- name: Wait until cloud-init finishes to grant the sudo access with no password
  raw: test -f /var/lib/cloud/instance/boot-finished
  retries: 30
  register: cmd_res
  changed_when: false
  until: cmd_res is success

- name: Configure swap file on the undercloud
  include_role:
    name: geerlingguy.swap

- name: HOSTNAME - Change the hostname
  hostname:
    name: undercloud.localdomain

- name: Red Hat Subscription management
  import_tasks: tasks/subscription.yml

- name: REPOSITORIES - Enable the needed repositories only
  rhsm_repository:
    name: "{{ RHOSP_version_supported[RHOSP_version].undercloud_repos }}"
    purge: yes

- name: MODULES - Enable and configure modules
  copy:
    dest: "/etc/dnf/modules.d/{{ item.name }}.module"
    content: |
      [{{ item.name }}]
      name={{ item.name }}
      stream={{ item.stream }}
      profiles={{ item.profiles }}
      state=enabled
  loop: "{{ RHOSP_version_supported[RHOSP_version].modules }}"

- name: PACKAGES - Install useful tools
  yum:
    name:
      - vim
      - wget
      - bash-completion
    state: latest

- name: PACKAGES - Update all packages
  yum:
    name: '*'
    state: latest
  notify: HANDLER - Reboot the machine

- name: CONFIGFILES - Create directories
  file:
    path: "/home/stack/{{ item }}"
    owner: stack
    group: stack
    state: directory
  loop:
    - images
    - templates
    - templates/nic-configs

- name: CONFIGFILES - Set container images prepare file
  template:
    src: "containers-prepare-parameter.yaml.j2"
    dest: "/home/stack/templates/containers-prepare-parameter.yaml"
    owner: stack
    group: stack

- name: CONFIGFILES - Set custom undercloud parameters
  copy:
    src: "templates/custom-undercloud-params.yaml"
    dest: "/home/stack/templates/custom-undercloud-params.yaml"
    owner: stack
    group: stack

- name: CONFIGFILES - Set undercloud configuration file
  template:
    src: "undercloud.conf.j2"
    dest: "/home/stack/undercloud.conf"
    owner: stack
    group: stack

- name: PACKAGES - Install needed packages
  yum:
    name: "{{ RHOSP_version_supported[RHOSP_version].packages }}"
    state: latest

- name: IMAGES - Unpack director images
  unarchive:
    src: "{{ item }}"
    dest: "/home/stack/images/"
    owner: stack
    group: stack
    remote_src: yes
  loop: "{{ RHOSP_version_supported[RHOSP_version].images_directories }}"

- name: IMAGES - Download images for testing
  get_url:
    url: "{{ item.url }}"
    dest: "images/{{ item.name }}"
    owner: stack
    group: stack
    timeout: 30
  loop:
    - url: "{{ RHOSP_version_supported[RHOSP_version].rhel_image.url }}"
      name: "{{ RHOSP_version_supported[RHOSP_version].rhel_image.name }}"
    - url: "https://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img"
      name: "cirros.qcow2"
  retries: 3
  delay: 10
  register: result
  until: result is not failed

- name: TEMPLATES - Prepare templates
  template:
    src: "{{ item }}.j2"
    dest: "/home/stack/templates/{{ item }}"
    owner: stack
    group: stack
  loop:
    - instackenv.yaml
    - node-info.yaml
    - custom-overcloud.yaml
    - network_data.yaml
    - custom-network-configuration.yaml
    - custom-ceph.yaml
    - vip_data.yaml

- name: TEMPLATES - Prepare roles_data.yaml depending on the version
  template:
    src: "roles_data_{{ RHOSP_version }}.yaml.j2"
    dest: "/home/stack/templates/roles_data.yaml"
    owner: stack
    group: stack

- name: TEMPLATES - Prepare the nic-configs templates
  template:
    src: "nic-configs/{{ item.nic_configs }}.j2"
    dest: "/home/stack/templates/nic-configs/{{ item.nic_configs }}"
    owner: stack
    group: stack
  loop: "{{ overcloud_roles }}"
  when: RHOSP_version != 17.0

- name: TEMPLATES - RHOSP 17.0 nic-config files
  template:
    src: "templates/nic-configs/nic-config.j2"
    dest: "/home/stack/templates/nic-configs/{{ item.profile }}.j2"
    owner: stack
    group: stack
  loop: "{{ overcloud_roles }}"
  when: RHOSP_version == 17.0

- name: SCRIPTS - Prepare the scripts
  template:
    src: "{{ item }}.j2"
    dest: "/home/stack/{{ item }}"
    mode: "755"
    owner: stack
    group: stack
  loop:
    - pre_deployment.sh
    - deploy.sh
    - post_deployment.sh
    - undeploy.sh
