- name: TEMPLATES - Create directories
  file:
    path: "/home/stack/{{ item }}"
    owner: stack
    group: stack
    state: directory
  loop:
    - templates
    - templates/nic-configs

- name: TEMPLATES - Prepare templates
  template:
    src: "{{ item }}.j2"
    dest: "/home/stack/templates/{{ item }}"
    owner: stack
    group: stack
  loop:
    - instackenv.yaml
    - node-info.yaml
    - custom-overcloud.yaml
    - network_data.yaml
    - custom-network-configuration.yaml
    - custom-ceph.yaml
    - vip_data.yaml

# TODO: Replace with a roles generation command in pre_deployment.sh
- name: TEMPLATES - Prepare roles_data.yaml depending on the version
  template:
    src: "roles_data_{{ RHOSP_version }}.yaml.j2"
    dest: "/home/stack/templates/roles_data.yaml"
    owner: stack
    group: stack

- name: TEMPLATES - Prepare the nic-configs templates
  template:
    src: "nic-configs/{{ item.profile }}.yaml.j2"
    dest: "/home/stack/templates/nic-configs/{{ item.profile }}.yaml"
    owner: stack
    group: stack
  loop: "{{ overcloud_roles }}"
  when: RHOSP_version != 17.0

- name: TEMPLATES - RHOSP 17.0 nic-config files
  template:
    src: "templates/nic-configs/nic-config.j2"
    dest: "/home/stack/templates/nic-configs/{{ item.profile }}.j2"
    owner: stack
    group: stack
  loop: "{{ overcloud_roles }}"
  when: RHOSP_version == 17.0

- name: SCRIPTS - Prepare the scripts
  template:
    src: "{{ item }}.j2"
    dest: "/home/stack/{{ item }}"
    mode: "755"
    owner: stack
    group: stack
  loop:
    - pre_deployment.sh
    - deploy.sh
    - post_deployment.sh
    - undeploy.sh