- name: PROFILES - Calculate roles count to use in the entire playbook
  set_fact:
    roles_count: |-
      {
      {%- for leaf in ([ DefaultLeaf0 ] + DCNLeafs) %}
        {{ leaf.name }}:
        {
        {%- for role in overcloud_roles %}
          {{ role.name }}: {{ (physical_machines | selectattr("openstack.role", "equalto", role.profile) | selectattr("openstack.leaf", "equalto", leaf.name) | list | count) + (libvirt_machines | selectattr("openstack.role", "equalto", role.profile) | selectattr("libvirt.hypervisor", "in", leaf.hypervisor) | list | count) }},
        {%- endfor %}
        },
      {%- endfor %}
      }

- name: PROFILES - Parse roles count fact
  set_fact:
    roles_count: "{{ roles_count | from_yaml }}"

- name: PROFILES - Check all libvirt machine profiles are virtual
  fail:
    msg: "ERROR in vm {{ item.name }}: Only virtual capable profiles can be used for libvirt machines."
  when:
    - item.openstack.role != 'undercloud'
    - not ((overcloud_roles | selectattr("profile", "equalto", item.openstack.role) | list | first).virtual | bool)
  loop: "{{ libvirt_machines }}"

- name: PROFILES - Check only the right profiles are used in libvirt machines for leafs
  fail:
    msg: "ERROR in vm {{ item.name }}: Only distributed capable profiles can be used in leafs."
  when:
    - item.openstack.role != 'undercloud'
    - item.libvirt.hypervisor not in DefaultLeaf0.hypervisor
    - not ((overcloud_roles | selectattr("profile", "equalto", item.openstack.role) | list | first).distributed | bool)
  loop: "{{ libvirt_machines }}"

- name: PROFILES - Check only the right profiles are used in physical machines for leafs
  fail:
    msg: "ERROR in physical {{ item.name }}: Only distributed capable profiles can be used in leafs."
  when:
    - item.openstack.leaf != DefaultLeaf0.name
    - not ((overcloud_roles | selectattr("profile", "equalto", item.openstack.role) | list | first).distributed | bool)
  loop: "{{ physical_machines }}"

- name: PROFILES - Check no more than the max amount of nodes for a profile is used in each leaf
  fail:
    msg: "No more than {{ item.1.max }} nodes are allowed for the role {{ item.1.name }} in leaf {{ item.0.name }}."
  when:
    - item.1.max is defined
    - roles_count[item.0.name][item.1.name] > item.1.max
  with_nested:
    - "{{ [ DefaultLeaf0 ] + DCNLeafs }}"
    - "{{ overcloud_roles }}"