- name: PROFILES - Check all vms profiles are virtual
  fail:
    msg: Please check your vms.yaml file and make sure the profiles chosen are the virtual ones.
  when: (item.name != 'undercloud') and (not item.profile.startswith('v'))
  loop: "{{ vms }}"

- name: PROFILES - Check all physical machines profiles are regular
  fail:
    msg: Please check your physical.yaml file and make sure the profiles chosen are the non virtual ones.
  when: item.profile.startswith('v')
  loop: "{{ physical }}"

- name: PROFILES - Check only one type of controllers is used
  fail:
    msg: Using Controller and VirtualControllers at the same time is not allowed.
  when: ((vms | selectattr("profile", "equalto", "vcontroller") | list | count) > 0) and ((physical | selectattr("profile", "equalto", "controller") | list | count) > 0)
