- name: SUBSCRIPTION - Check subscription-manager status
  shell: "subscription-manager status"
  register: status
  changed_when: false
  failed_when: false

- name: SUBSCRIPTION - Register, attach and set release (with OrgID and Activation Key)
  redhat_subscription:
    state: present
    org_id: "{{ rh_orgid }}"
    activationkey: "{{ rh_activationkey }}"
    pool: "Red Hat OpenStack"
    syspurpose:
      role: "Red Hat Enterprise Linux Server"
      service_level_agreement: "Self-Support"
      usage: "Development/Test"
    release: "{{ RHOSP_version_supported[RHOSP_version].rhel_release }}"
    force_register: yes
  when: (status is not search('Current')) and (status is not search('Content Access Mode')) and ( (rh_orgid is defined) and (rh_activationkey is defined) )
  failed_when: false

- name: SUBSCRIPTION - Register, attach and set release (with username and password)
  redhat_subscription:
    state: present
    username: "{{ rh_username }}"
    password: "{{ rh_password }}"
    pool: "Red Hat OpenStack"
    syspurpose:
      role: "Red Hat Enterprise Linux Server"
      service_level_agreement: "Self-Support"
      usage: "Development/Test"
    release: "{{ RHOSP_version_supported[RHOSP_version].rhel_release }}"
    force_register: yes
  when: (status is not search('Current')) and (status is not search('Content Access Mode')) and ( (rh_orgid is not defined) or (rh_activationkey is not defined) )
  failed_when: false

- name: SUBSCRIPTION - Check subscription-manager status again
  shell: "subscription-manager status"
  register: status_new
  changed_when: false
  failed_when: (status_new is not search('Current')) and (status_new is not search('Content Access Mode'))
