---
- name: Local configuration for the Lab to work
  hosts: infrastructure
  vars_files:
    - vars/vms.yml
    - vars/networks.yml
  become: no

  tasks:
    - name: Ensure virtualization packages are installed and services are running
      import_tasks: tasks/01.01_virt_pkg_svc.yml

    - name: Configure libvirt networks
      import_tasks: tasks/01.02_libvirt_networks.yml

    - name: Configure libvirt storage pools and images
      import_tasks: tasks/01.03_libvirt_storage.yml

    - name: Configure libvirt domains
      import_tasks: tasks/01.04_libvirt_domains.yml

    - name: Install and configure VirtualBMC
      import_tasks: tasks/01.05_virtualbmc.yml

    - name: Create an ssh key
      import_tasks: tasks/01.06_ssh_key.yml
