---
- name: Undercloud installation
  hosts: undercloud
  vars_files:
    - vault_credentials.yaml

  tasks:
    - name: Hostname management
      import_tasks: tasks/03.01_hostname.yml

    - name: Red Hat Subscription management
      import_tasks: tasks/03.02_subscription.yml

    - name: Manage repositories, modules, services and packages
      import_tasks: tasks/03.03_repos_mods_pkgs.yml

    - name: Set the configuration files
      import_tasks: tasks/03.04_config_files.yml

    - name: Configure NetworkManager and network services
      import_tasks: tasks/03.05_network.yml

  handlers:
    - name: Reboot the machine
      reboot:
        reboot_timeout: 120

    - name: Restart network service
      service:
        name: network
        state: restarted
