---
- name: Infrastructure configuration
  hosts: infrastructure
  vars_files:
    - vars/options.yml
    - vars/vms.yml
    - vars/networks.yml

  pre_tasks:
    - name: Set ansible_user to the admin current user
      set_fact:
        ansible_user: admin
  
  roles:
    - role: RHOSP-virt-infra

- name: Openstack configuration
  hosts: openstack
  vars_files:
    - vault_credentials.yaml
    - vars/options.yml
    - vars/networks.yml
    - vars/vms.yml
    - vars/physical.yml
  gather_facts: no
  
  pre_tasks:
    - name: Wait for the undercloud to come up
      wait_for_connection:
        timeout: 120
      when: create | bool

    - name: Gathering facts
      setup:
      when: create | bool
  
  roles:
    - role: RHOSP-undercloud
      when: create | bool
