---
- name: Infrastructure configuration
  hosts: infrastructure
  vars_files:
    - vars/vms.yml
    - vars/networks.yml
  become: no
  roles:
    - role: RHOSP-virt-infra
      vars:
        cleanup: False # Set to True if you want to clean up the lab and start it from scratch
        create: True # Set to False if you want not to create the lab resources

#- name: Openstack configuration
#  hosts: openstack
#  vars_files:
#    - vars/vms.yml
#    - vars/physical.yml
#  roles:
#    - role: RHOSP-undercloud
