---
- name: Local configuration
  import_playbook: 01_local_installation.yml

- name: Undercloud configuration
  import_playbook: 02_undercloud_configuration.yml

- name: Undercloud installation
  import_playbook: 03_undercloud_installation.yml

- name: Overcloud deploy
  import_playbook: 04_overcloud_deploy.yml
