---
# defaults file for RHOSP-virt-infra

# RHOSP version
RHOSP_version: 17.0

# Cleaning and creating parameters
cleanup: False
create: True

# overcloud parameters
external_if: eno1
overcloud_ip: 10.0.0.254
forward_network: RHOSPVirtLab_external
forwarded_ports:
  - 80
  - 6080
  - 5000

# DCN leafs
DCNLeafs: []
  # - name: leaf1
  #   subnet:
  #     name: leaf1-subnet
  #     cidr: 192.168.25.0/24
  #     dhcp_start: 192.168.25.5
  #     dhcp_end: 192.168.25.55
  #     inspection_iprange: 192.168.25.100,192.168.25.120
  #     gateway: 192.168.25.1
  #     masquerade: true
  #   hypervisor: <hypervisor_name>
  #   networks_prefix: 172.17

# vms is a list to define the virtual machines to be created. The role defines a minimum of one undercloud, one controller node and one compute node
vms:
  - name: undercloud
    hypervisor: localhost
    title: 'RHOSPVirtLab Undercloud'
    profile: 'undercloud'
    memory: 6291456
    vcpus: 2
    bmcport: 6230
    mac: '0c:1f:0d:10:00'
    disk_size: 107374182400
    backing_store: "{{ RHOSP_version_supported[RHOSP_version].rhel_image.name }}"
    cdrom: 'undercloud-init.iso'
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_management: '192.168.250.10'
  - name: vcontroller0
    hypervisor: localhost
    title: 'RHOSPVirtLab Virtual Controller 0'
    profile: 'vcontroller'
    memory: 8388608
    vcpus: 2
    bmcport: 6231
    mac: '0c:1f:0d:11:00'
    disk_size: 53687091200
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_external: ''
  - name: vcompute0
    hypervisor: localhost
    title: 'RHOSPVirtLab Virtual Compute 0'
    profile: 'vcompute'
    memory: 6291456
    vcpus: 4
    bmcport: 6234
    mac: '0c:1f:0d:12:00'
    disk_size: 53687091200
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_external: ''

# networks is a list to define the virtual networks to be created
networks:
  - name: RHOSPVirtLab_ctlplane
    hypervisor: localhost
    bridge: br-ctlplane
    forward: open
    mac_suffix: '00'
    ipv4:
      address: '192.168.24.254'
      netmask: '255.255.255.0'
      dhcp: false
  - name: RHOSPVirtLab_external
    hypervisor: localhost
    bridge: br-external
    forward: open
    mac_suffix: '05'
    ipv4:
      address: '10.0.0.1'
      netmask: '255.255.255.0'
      dhcp: false
  - name: RHOSPVirtLab_management
    hypervisor: localhost
    bridge: br-management
    forward: nat
    mac_suffix: '0f'
    ipv4:
      address: '192.168.250.1'
      netmask: '255.255.255.0'
      dhcp:
        start: '192.168.250.100'
        end: '192.168.250.254'
        hosts: true

# Default leaf configuration
DefaultLeaf0:
  name: overcloud
  hypervisor: localhost
  subnet:
    name: ctlplane-subnet
    cidr: 192.168.24.0/24
    dhcp_start: 192.168.24.5
    dhcp_end: 192.168.24.55
    inspection_iprange: 192.168.24.100,192.168.24.120
    gateway: 192.168.24.254
    masquerade: false
  networks:
    Tenant:
      prefix: '172.16.0'
      vlan: 10
      network: RHOSPVirtLab_ctlplane
    Storage:
      prefix: '172.16.1'
      vlan: 20
      network: RHOSPVirtLab_ctlplane
    InternalApi:
      prefix: '172.16.2'
      vlan: 30
      network: RHOSPVirtLab_ctlplane
    StorageMgmt:
      prefix: '172.16.3'
      vlan: 40
      network: RHOSPVirtLab_ctlplane
    External:
      prefix: '10.0.0'
      network: RHOSPVirtLab_external
    Management:
      prefix: '10.0.1'
      vlan: 60
      network: RHOSPVirtLab_ctlplane