---
# defaults file for RHOSP-virt-infra

# RHOSP version
RHOSP_version: 16.2

# Cleaning and creating parameters
cleanup: False
create: True

# overcloud parameters
external_if: eno1
overcloud_ip: 10.0.0.254
forwarded_ports:
  - 80  
  - 6080
  - 5000

# vms is a list to define the virtual machines to be created. The role defines a minimum of one undercloud, one controller node and one compute node
vms:
  - name: undercloud
    title: 'RHOSPVirtLab Undercloud'
    profile: 'undercloud'
    memory: 6291456
    vcpus: 2
    bmcport: 6230
    mac: '0c:1f:0d:10:00'
    disk_size: 107374182400
    backing_store: "{{ RHOSP_version_supported[RHOSP_version].rhel_image.name }}"
    cdrom: 'undercloud-init.iso'
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_management: '192.168.250.10'
  - name: controller0
    title: 'RHOSPVirtLab Controller 0'
    profile: 'control'
    memory: 8388608
    vcpus: 2
    bmcport: 6231
    mac: '0c:1f:0d:11:00'
    disk_size: 53687091200
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''
  - name: compute0
    title: 'RHOSPVirtLab Compute 0'
    profile: 'compute'
    memory: 6291456
    vcpus: 4
    bmcport: 6234
    mac: '0c:1f:0d:12:00'
    disk_size: 53687091200
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''

# networks is a list to define the virtual networks to be created
networks:
  - name: RHOSPVirtLab_ctlplane
    bridge: br-ctlplane
    forward: bridge
    mac_suffix: '00'
    ipv4: false
    hypervisor_if: eno2
    vlans:
      - name: External
        id: "{{ network_data_vlans.External }}"
        address: '10.0.0.1/24'
      - name: InternalApi
        id: "{{ network_data_vlans.InternalApi }}"
        address: ''
      - name: Storage
        id: "{{ network_data_vlans.Storage }}"
        address: ''
      - name: StorageMgmt
        id: "{{ network_data_vlans.StorageMgmt }}"
        address: ''
      - name: Tenant
        id: "{{ network_data_vlans.Tenant }}"
        address: ''
  - name: RHOSPVirtLab_management
    bridge: br-management
    forward: nat
    mac_suffix: '0f'
    vlans: []
    ipv4:
      address: '192.168.250.1'
      netmask: '255.255.255.0'
      dhcp:
        start: '192.168.250.100'
        end: '192.168.250.254'
        hosts: true
