- name: Ensure the directory exists
  file:
    path: ~/.ssh
    owner: ansible
    group: ansible
    state: directory

- name: SSHKEY - Create ssh key
  openssh_keypair:
    path: ~/.ssh/id_rsa
    owner: ansible
    group: ansible
