- name: ROOTDISK - Install growpart
  yum:
    name: cloud-utils-growpart
    state: latest

- name: ROOTDISK - Extend the root partition to fill all available space
  command: "growpart /dev/sda 3"
  when: ansible_devices.sda.partitions.sda3.size | human_to_bytes < 100000000000
  notify:
    - Resize root filesystem
    - Reboot the machine
