- name: SUBSCRIPTION - Register, attach and set release
  redhat_subscription:
    state: present
    username: "{{ rh_username }}"
    password: "{{ rh_password }}"
    pool: '^Red Hat OpenStack'
    auto_attach: true
    release: '8.2'
  notify: Reboot the machine
