- name: VIRTUALBMC - Get node states
  shell: "/usr/local/bin/vbmc list 2>/dev/null | awk '/{{ item.name }}/ {print $4,$8}'"
  register: vbmc_status
  loop: "{{ vms }}"
  changed_when: False

- name: VIRTUALBMC - Delete nodes
  command: "/usr/local/bin/vbmc delete {{ item.item.name }}"
  when: item.stdout
  loop: "{{ vbmc_status.results }}"
