- name: STORAGE - Gather facts about libvirt storage pools
  community.libvirt.virt_pool:
    command: facts

- name: STORAGE - Deactivate the pool
  community.libvirt.virt_pool:
    state: inactive
    name: "{{ item }}"
  loop:
    - RHOSPVirtLab_storage

- name: STORAGE - Delete the pool
  community.libvirt.virt_pool:
    command: undefine
    name: "{{ item }}"
  when: ansible_libvirt_pools[item] is defined
  loop:
    - RHOSPVirtLab_storage

- name: STORAGE - Gather facts about libvirt storage pools
  community.libvirt.virt_pool:
    command: facts

- name: STORAGE - Find the disk and cloud-init files for each libvirt machine
  find:
    paths: "{{ pool_location }}"
    patterns:
      - "{{ item.name }}_*.qcow2"
      - "{{ item.name }}-init.iso"
  loop: "{{ libvirt_machines }}"
  when: inventory_hostname in item.libvirt.hypervisor
  register: machine_disk_files

- name: STORAGE - Delete the disk files
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ machine_disk_files.results | selectattr('files', 'defined') | map(attribute='files') | flatten }}"
  loop_control:
    label: "{{ item.path }}"
