- name: DOMAINS - List libvirt VMs
  community.libvirt.virt:
    command: list_vms
  register: all_vms

- name: DOMAINS - List libvirt VMs
  community.libvirt.virt:
    command: list_vms
    state: running
  register: running_vms

- name: DOMAINS - Destroy the domain
  community.libvirt.virt:
    command: destroy
    name: "{{ item.name }}"
  when: item.name in running_vms.list_vms
  loop: "{{ vms }}"

- name: DOMAINS - Undefine the domain
  community.libvirt.virt:
    command: undefine
    name: "{{ item.name }}"
  when: item.name in all_vms.list_vms
  loop: "{{ vms }}"
  ignore_errors: yes
  register: undefine_result

- name: DOMAINS - Undefine the domain if fails
  shell: "virsh undefine --nvram {{ item.name }}"
  when: item.name in all_vms.list_vms and undefine_result.failed and (undefine_result.results | selectattr("item.name", "equalto", item.name) | list | first).failed
  loop: "{{ vms }}"
