- name: FIREWALL - Clean port forwarding rules
  firewalld:
    rich_rule: rule family=ipv4 forward-port port={{ item }} protocol=tcp to-port={{ item }} to-addr={{ overcloud_ip }}
    zone: public
    permanent: yes
    immediate: yes
    state: disabled
  loop: "{{ forwarded_ports }}"
  when: inventory_hostname == 'localhost'