- name: NETWORKING - Define only the network configuration for the public interface of the DCN hypervisors without static routes
  set_fact:
    network_connections: "{{ network_connections + [connection] }}"
  vars:
    connection:
      name: "{{ hypervisor_external_if }}"
      interface_name: "{{ hypervisor_external_if }}"
      type: ethernet
      autoconnect: yes
      state: up
      ip:
        dhcp4: yes
  when: inventory_hostname != 'localhost'

- name: NETWORKING - Define only the network configuration for the public interface of the localhost hypervisor without static routes
  set_fact:
    network_connections: "{{ network_connections + [connection] }}"
  vars:
    connection:
      name: "{{ external_if }}"
      interface_name: "{{ external_if }}"
      type: ethernet
      autoconnect: yes
      state: up
      ip:
        dhcp4: yes
  when: inventory_hostname == 'localhost'

- name: NETWORKING - Delete all other interfaces
  set_fact:
    network_connections: "{{ network_connections + [connection] }}"
  vars:
    connection:
      persistent_state: absent

- name: NETWORKING - Configure network using system role
  import_role:
    name: rhel-system-roles.network
  vars:
    network_allow_restart: yes

- name: NETWORKING - Gather facts again to get interfaces
  setup: