- name: VIRTUALBMC - Get node states
  shell: "{{ RHEL_version_supported[ansible_distribution_version].vbmc_path }} list 2>/dev/null | awk '/{{ item.name }}/ {print $4,$8}'"
  register: vbmc_status
  loop: "{{ vms }}"
  changed_when: False

- name: VIRTUALBMC - Delete nodes
  command: "{{ RHEL_version_supported[ansible_distribution_version].vbmc_path }} delete {{ item.item.name }}"
  when: item.stdout
  loop: "{{ vbmc_status.results }}"
