- name: NETWORKS - Gather facts about libvirt networks
  community.libvirt.virt_net:
    command: facts

- name: NETWORKS - Destroy the network
  community.libvirt.virt_net:
    command: destroy
    name: "{{ item.name }}"
  loop: "{{ networks }}"
  when:
    - inventory_hostname in item.hypervisor
    - ansible_libvirt_networks[item.name] is defined

- name: NETWORKS - Undefine the network
  community.libvirt.virt_net:
    command: undefine
    name: "{{ item.name }}"
  loop: "{{ networks }}"
  when:
    - inventory_hostname in item.hypervisor
    - ansible_libvirt_networks[item.name] is defined
