- name: VIRTUALBMC - Get node states
  shell: "{{ vbmc_path }} list 2>/dev/null | awk '/{{ item.name }}/ {print $4,$8}'"
  register: vbmc_status
  loop: "{{ vms }}"
  changed_when: False
  when: inventory_hostname in item.hypervisor

- name: VIRTUALBMC - Delete nodes
  command: "{{ vbmc_path }} delete {{ item.item.name }}"
  loop: "{{ vbmc_status.results }}"
  when:
    - item.stdout is defined
    - item.stdout
