- name: DOMAINS - List libvirt VMs
  community.libvirt.virt:
    command: list_vms
  register: all_vms
  become: yes

- name: DOMAINS - Define the domain from the template
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'domain.xml.j2') }}"
    autostart: yes
  loop: "{{ libvirt_machines }}"
  become: yes
  notify: HANDLER - Clean known_hosts file
  when:
    - inventory_hostname == item.libvirt.hypervisor
    - item.name not in all_vms.list_vms

- name: DOMAINS - Stop machines whose cloud-init ISO changed in order to re-apply it on reboot
  community.libvirt.virt:
    name: "{{ item }}"
    state: shutdown
  become: yes
  loop: "{{ cloud_init_changed_machines | default([]) }}"
  when: item in all_vms.list_vms

- name: DOMAINS - Wait for those machines to stop
  community.libvirt.virt:
    command: list_vms
    state: running
  become: yes
  register: running_vms
  retries: 3
  delay: 15
  until: (cloud_init_changed_machines | default([]) | intersect(running_vms.list_vms) | length) == 0
  when: (cloud_init_changed_machines | default([]) | length) > 0

- name: DOMAINS - Ensure undercloud domain is running
  community.libvirt.virt:
    name: undercloud
    state: running
  become: yes
  when:
    - inventory_hostname == 'localhost'
    - not undercloud_is_physical | bool

- name: DOMAINS - Wait for the undercloud to start
  community.libvirt.virt:
    command: list_vms
    state: running
  become: yes
  register: running_vms
  retries: 3
  delay: 15
  until: '"undercloud" in running_vms.list_vms'
  when:
    - inventory_hostname == 'localhost'
    - not undercloud_is_physical | bool

- name: DOMAINS - Add management IPs entries to /etc/hosts on the local machines
  lineinfile:
    path: "/etc/hosts"
    regexp: "{{ hostvars[item.name].ansible_host }}\t{{ item.name }}"
    line: "{{ hostvars[item.name].ansible_host }}\t{{ item.name }}"
    state: present
  loop: "{{ libvirt_machines }}"
  become: yes
  when:
    - inventory_hostname == item.libvirt.hypervisor
    - item.libvirt.network.interfaces | selectattr('management', 'defined') | selectattr('management') | list | length > 0
    - hostvars[item.name] is defined
    - hostvars[item.name].ansible_host is defined

- name: DOMAINS - Add the physical undercloud entry to /etc/hosts on the local machine
  lineinfile:
    path: "/etc/hosts"
    regexp: "{{ hostvars['undercloud'].ansible_host }}\tundercloud"
    line: "{{ hostvars['undercloud'].ansible_host }}\tundercloud"
    state: present
  become: yes
  when:
    - inventory_hostname == 'localhost'
    - undercloud_is_physical | bool
    - hostvars['undercloud'] is defined
    - hostvars['undercloud'].ansible_host is defined

- name: DOMAINS - Add overcloud IP entry to /etc/hosts on the local machines
  lineinfile:
    path: "/etc/hosts"
    regexp: "{{ overcloud_ip }}\tovercloud"
    line: "{{ overcloud_ip }}\tovercloud"
    state: present
  become: yes

