- name: STORAGE - Create storage directory
  file:
    path: "{{ pool_location }}"
    state: directory
    mode: "0777"
  become: yes

- name: STORAGE - Define the pool from the template
  community.libvirt.virt_pool:
    command: define
    name: "{{ item }}"
    xml: '{{ lookup("template", "{{ item }}.xml.j2") }}'
  when: ansible_libvirt_pools[item] is not defined
  loop:
    - RHOSPVirtLab_storage
  become: yes

- name: STORAGE - Gather facts about libvirt storage pools
  community.libvirt.virt_pool:
    command: facts

- name: STORAGE - Activate the pool
  community.libvirt.virt_pool:
    state: active
    name: "{{ item }}"
  when: (ansible_libvirt_pools[item] is defined) and (ansible_libvirt_pools[item]['status'] != 'active')
  loop:
    - RHOSPVirtLab_storage
  become: yes

- name: STORAGE - Enable autostart for the pool
  community.libvirt.virt_pool:
    autostart: yes
    name: "{{ item }}"
  when: (ansible_libvirt_pools[item] is defined) and (ansible_libvirt_pools[item]['autostart'] != 'yes')
  loop:
    - RHOSPVirtLab_storage
  become: yes

- name: STORAGE - Generate per-machine cloud-init ISOs
  include_tasks: create_libvirt_cloud_init.yml
  loop: "{{ libvirt_machines | selectattr('pre_provisioned', 'defined') | selectattr('pre_provisioned') | list }}"
  loop_control:
    loop_var: machine
    label: "{{ machine.name }}"
  when: inventory_hostname in machine.libvirt.hypervisor

- name: STORAGE - Download the rhel base image
  get_url:
    url: "{{ CustomRhelImage }}"
    dest: "{{ pool_location }}/{{ RHOSP_version_supported[RHOSP_version].rhel_image.name }}"
    mode: "0777"
    owner: root
    group: root
    timeout: 30
  retries: 3
  delay: 10
  register: result
  until: result is not failed
  when: inventory_hostname == 'localhost'

- name: STORAGE - Check if the rhel base image exists
  stat:
    path: "{{ pool_location }}/{{ RHOSP_version_supported[RHOSP_version].rhel_image.name }}"
  register: rhel_image_stat
  when: inventory_hostname == 'localhost'

- name: STORAGE - Fail when the rhel base image does not exist
  fail:
    msg: "{{ RHOSP_version_supported[RHOSP_version].rhel_image.name }} does not exist"
  when:
    - inventory_hostname == 'localhost'
    - not rhel_image_stat.stat.exists

- name: Download and unpack libguestfs binary appliance (unsupported workaround https://access.redhat.com/solutions/4073061)
  unarchive:
    src: "http://download.libguestfs.org/binaries/appliance/appliance-1.46.0.tar.xz"
    dest: "/home/{{ ansible_user }}/"
    remote_src: yes
    mode: "0777"
  when: (ansible_distribution_version | int < 8) and (RHOSP_version | int >= 16)

- name: STORAGE - Create and prepare the disk volumes for each libvirt machine
  include_tasks: create_libvirt_disks.yml
  loop: "{{ libvirt_machines }}"
  loop_control:
    loop_var: machine
  when: inventory_hostname in machine.libvirt.hypervisor
