- name: NETWORKS - Create libvirt hooks directory
  file:
    path: "/etc/libvirt/hooks"
    state: directory
    mode: "755"
    owner: root
    group: root
  when: inventory_hostname == 'localhost'

- name: NETWORKS - Add hook for libvirt networks (hack) in order to allow port-forwarding when the network is forwarding route
  template:
    src: "network-hook.j2"
    dest: "/etc/libvirt/hooks/network"
    mode: "755"
    owner: root
    group: root
  become: yes
  notify: HANDLER - restart libvirtd service
  when:
    - inventory_hostname == 'localhost'
    - (networks | selectattr('name', 'search', DefaultLeaf0.networks.External.network) | list | first).forward == 'nat'

- name: NETWORKS - Gather facts about libvirt networks
  community.libvirt.virt_net:
    command: facts

- name: NETWORKS - Define the network from the template
  community.libvirt.virt_net:
    command: define
    name: "{{ item.name }}"
    xml: "{{ lookup('template', 'network.xml.j2') }}"
  loop: "{{ networks }}"
  become: yes
  when:
    - inventory_hostname in item.hypervisor
    - ansible_libvirt_networks[item.name] is not defined

- name: NETWORKS - Gather facts about libvirt networks again
  community.libvirt.virt_net:
    command: facts

- name: NETWORKS - Activate the network
  community.libvirt.virt_net:
    state: active
    name: "{{ item.name }}"
  loop: "{{ networks }}"
  become: yes
  when:
    - inventory_hostname in item.hypervisor
    - ansible_libvirt_networks[item.name]['state'] != 'active'

- name: NETWORKS - Enable autostart for the network
  community.libvirt.virt_net:
    autostart: yes
    name: "{{ item.name }}"
  loop: "{{ networks }}"
  become: yes
  when:
    - inventory_hostname in item.hypervisor
    - ansible_libvirt_networks[item.name]['autostart'] != 'yes'
