- name: VIRTUALBMC - Get node states
  shell: "{{ RHEL_version_supported[ansible_distribution_version].vbmc_path }} list 2>/dev/null | awk '/{{ item.name }}/ {print $4,$8}'"
  register: vbmc_status
  loop: "{{ vms }}"
  changed_when: False

- name: VIRTUALBMC - Ensure node exists
  command: "{{ RHEL_version_supported[ansible_distribution_version].vbmc_path }} add --username admin --password admin --address 192.168.250.1 --port {{ item.item.bmcport }} {{ item.item.name }}"
  when: not item.stdout
  loop: "{{ vbmc_status.results }}"

- name: VIRTUALBMC - Get node states again
  shell: "{{ RHEL_version_supported[ansible_distribution_version].vbmc_path }} list 2>/dev/null | grep running | awk '/{{ item.name }}/ {print $4,$8}'"
  register: vbmc_running
  loop: "{{ vms }}"
  changed_when: False

- name: VIRTUALBMC - Start node
  command: "{{ RHEL_version_supported[ansible_distribution_version].vbmc_path }} start {{ item.item.name }}"
  when: not item.stdout
  loop: "{{ vbmc_running.results }}"

- name: VIRTUALBMC - Get service facts
  service_facts:

- name: VIRTUALBMC - Ensure port rules are configured to the firewall
  firewalld:
    port: "{{ item.bmcport }}/udp"
    zone: "libvirt"
    permanent: yes
    immediate: yes
    state: enabled
  when: (ansible_facts.services['firewalld.service'] is defined) and (ansible_facts.services['firewalld.service'].state == 'running')
  loop: "{{ vms }}"
  become: yes
