---
# tasks file for RHOSP-virt-infra

- name: CHECKS - Perform some checks
  import_tasks: tasks/checks.yml

- name: SETUP - Make the hypervisor setup
  import_tasks: tasks/setup.yml

# Cleanup process

- name: DHCRELAY - Clean DHCP relay
  import_tasks: clean_dhcrelay.yml
  when:
    - cleanup | bool
    - DCNLeafs | length > 0

- name: FIREWALL - Clean firewall
  import_tasks: clean_firewall.yml
  when: cleanup | bool

- name: NETWORKING - Clean network profiles
  import_tasks: clean_network_profiles.yml
  when:
    - cleanup | bool
    - not create | bool

- name: VIRTUALBMC - Clean VirtualBMC
  import_tasks: clean_virtualbmc.yml
  when: cleanup | bool

- name: LIBVIRT - Clean libvirt domains
  import_tasks: clean_libvirt_domains.yml
  when: cleanup | bool

- name: LIBVIRT - Clean libvirt storage pools and images
  import_tasks: clean_libvirt_storage.yml
  when: cleanup | bool

- name: LIBVIRT - Clean libvirt networks
  import_tasks: clean_libvirt_networks.yml
  when: cleanup | bool

# Create process

- name: NETWORKING - Create network profiles
  import_tasks: create_network_profiles.yml
  when: create | bool

- name: LIBVIRT - Configure libvirt networks
  import_tasks: create_libvirt_networks.yml
  when: create | bool

- name: LIBVIRT - Configure libvirt storage pools and images
  import_tasks: create_libvirt_storage.yml
  when: create | bool

- name: LIBVIRT - Configure libvirt domains
  import_tasks: create_libvirt_domains.yml
  when: create | bool

- name: VIRTUALBMC - Configure VirtualBMC
  import_tasks: create_virtualbmc.yml
  when: create | bool

- name: FIREWALL - Configure firewall
  import_tasks: configure_firewall.yml
  when: create | bool

- name: DHCRELAY - Configure DHCP relay
  import_tasks: configure_dhcrelay.yml
  when:
    - create | bool
    - DCNLeafs | length > 0