---
# defaults file for RHOSP-undercloud

# overcloud parameters
overcloud_ip: 10.0.0.254

# vms is a list to define the virtual machines to be created. The role defines a minimum of one undercloud, one controller node and one compute node
vms:
  - name: undercloud
    title: 'RHOSPVirtLab Undercloud'
    profile: 'undercloud'
    memory: 6291456
    vcpus: 2
    bmcport: 6230
    mac: '0c:1f:0d:10:00'
    disk_size: 107374182400
    backing_store: 'rhel-8.4-x86_64-kvm.qcow2'
    cdrom: 'undercloud-init.iso'
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_management: '192.168.250.10'
  - name: controller0
    title: 'RHOSPVirtLab Controller 0'
    profile: 'control'
    memory: 8388608
    vcpus: 2
    bmcport: 6231
    mac: '0c:1f:0d:11:00'
    disk_size: 53687091200
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_storage: ''
      RHOSPVirtLab_storage_mgmt: ''
      RHOSPVirtLab_internal_api: ''
      RHOSPVirtLab_tenant: ''
      RHOSPVirtLab_external: ''
  - name: compute0
    title: 'RHOSPVirtLab Compute 0'
    profile: 'compute'
    memory: 6291456
    vcpus: 4
    bmcport: 6234
    mac: '0c:1f:0d:12:00'
    disk_size: 53687091200
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_storage: ''
      RHOSPVirtLab_storage_mgmt: ''
      RHOSPVirtLab_internal_api: ''
      RHOSPVirtLab_tenant: ''
      RHOSPVirtLab_external: ''

# physical is a list to define the physical machines to be connected. The role doesn't define any by default
physical:

# networks is a list to define the virtual networks to be created
networks:
  - name: RHOSPVirtLab_ctlplane
    bridge: br-ctlplane
    forward: false
    mac_suffix: '00'
    ipv4: false
    hypervisor_if: eno2
  - name: RHOSPVirtLab_storage
    bridge: br-storage
    forward: false
    mac_suffix: '01'
    ipv4: false
  - name: RHOSPVirtLab_storage_mgmt
    bridge: br-storage-mgmt
    forward: false
    mac_suffix: '02'
    ipv4: false
  - name: RHOSPVirtLab_internal_api
    bridge: br-internal-api
    forward: false
    mac_suffix: '03'
    ipv4: false
  - name: RHOSPVirtLab_tenant
    bridge: br-tenant
    forward: false
    mac_suffix: '04'
    ipv4: false
  - name: RHOSPVirtLab_external
    bridge: br-external
    forward: route
    mac_suffix: '05'
    ipv4:
      address: '10.0.0.1'
      netmask: '255.255.255.0'
      dhcp: false
  - name: RHOSPVirtLab_management
    bridge: br-management
    forward: nat
    mac_suffix: '0f'
    ipv4:
      address: '192.168.250.1'
      netmask: '255.255.255.0'
      dhcp:
        start: '192.168.250.100'
        end: '192.168.250.254'
        hosts: true

# repositories to be enabled on the undercloud
repositories:
  - rhel-8-for-x86_64-baseos-rpms
  - rhel-8-for-x86_64-appstream-rpms
  - rhel-8-for-x86_64-highavailability-rpms
  - ansible-2.9-for-rhel-8-x86_64-rpms
  - openstack-16.2-for-rhel-8-x86_64-rpms
  - fast-datapath-for-rhel-8-x86_64-rpms
  - rhceph-4-tools-for-rhel-8-x86_64-rpms
