---
# defaults file for RHOSP-undercloud

# RHOSP version
RHOSP_version: 17.0

# Cleaning and creating parameters
create: True

# overcloud parameters
overcloud_ip: 10.0.0.254

# dns and ntp servers
dns_servers:
  - '8.8.8.8'
  - '8.8.4.4'
ntp_servers: 
  - '0.pool.ntp.org'
  - '1.pool.ntp.org'
  - '2.pool.ntp.org'
  - '3.pool.ntp.org'

# vlans to use in the network-data
network_data_vlans:
  External: 10
  InternalApi: 20
  Storage: 30
  StorageMgmt: 40
  Tenant: 50
  Management: 60

# interfaces to use in each nic-config
interfaces:
  VirtualController:
    ControlPlane: nic1
    External: nic2
  VirtualCompute:
    ControlPlane: nic1
    External: nic2
  VirtualCephStorage:
    ControlPlane: nic1
    External: nic2
  VirtualComputeHCI:
    ControlPlane: nic1
    External: nic2
  Controller:
    ControlPlane: nic2
    External: nic3
  Compute:
    ControlPlane: nic2
    External: nic3
  ComputeOvsDpdk:
    ControlPlane: nic2
    External: nic3
    DpdkBonds:
      - name: dpdkbond0
        ports:
          - name: dpdk0
            interface: nic4
            driver: vfio-pci
          - name: dpdk1
            interface: nic5
            driver: vfio-pci
  ComputeOvsDpdkSriov:
    ControlPlane: nic2
    External: nic3v0
    Sriov:
      - device: nic3
        numvfs: 8
    DpdkBonds:
      - name: dpdkbond0
        ports:
          - name: dpdk0
            interface: nic3v1
            driver: vfio-pci
          - name: dpdk1
            interface: nic3v2
            driver: vfio-pci
  ComputeSriov:
    ControlPlane: nic2
    External: nic3v0
    Sriov:
      - device: nic3
        numvfs: 8
  ComputeOvsHwOffload:
    ControlPlane: nic2
    External: nic3v0
    Sriov:
      - device: nic3
        numvfs: 8
  CephStorage:
    ControlPlane: nic2
    External: nic3
  ComputeHCI:
    ControlPlane: nic2
    External: nic3

# All computes default properties
BridgeMappings: 'datacentre:br-ex'
NetworkVlanRanges: 'datacentre:1:1000,sriov1:11:19'

# ComputeSriov default properties
ComputeSriovProperties:
  isolcpus: '8-19'
  hugepagesz: '1GB'
  hugepages: 32
  kernelargs: 'iommu=pt intel_iommu=on'
  physicaldevmappings: 'sriov1:ens1f1'
  dedicatedcpus: '8-19'
  sharedcpus: '4-7'
  hostmemory: 8192
  pcipassthrough:
    - devname: ens1f1
      network: 'sriov1'
      trusted: true

# ComputeOvsHwOffload default properties
ComputeOvsHwOffloadProperties:
  isolcpus: '8-19'
  hugepagesz: '1GB'
  hugepages: 32
  kernelargs: 'iommu=pt intel_iommu=on'
  physicaldevmappings: 'offload1:ens1f1'
  dedicatedcpus: '8-19'
  sharedcpus: '4-7'
  hostmemory: 8192
  pcipassthrough:
    - devname: ens1f1
      network: 'sriov1'
      trusted: true

# ComputeOvsDpdk default properties
ComputeOvsDpdkProperties:
  isolcpus: '6-23,30-47'
  hugepagesz: '1GB'
  hugepages: 32
  kernelargs: 'iommu=pt intel_iommu=on'
  dedicatedcpus: '8-23,32-47'
  sharedcpus: '6-7,30-31'
  hostmemory: 8192
  socketmemory: '4096,4096'
  memorychannels: '4'
  ovsdpdkcorelist: '2,26,3,27'
  ovspmdcorelist: '4,28,5,29'

# ComputeOvsDpdkSriov default properties
ComputeOvsDpdkSriovProperties:
  isolcpus: '6-23,30-47'
  hugepagesz: '1GB'
  hugepages: 32
  kernelargs: 'iommu=pt intel_iommu=on'
  dedicatedcpus: '8-23,32-47'
  sharedcpus: '6-7,30-31'
  hostmemory: 8192
  socketmemory: '4096,4096'
  memorychannels: '4'
  ovsdpdkcorelist: '2,26,3,27'
  ovspmdcorelist: '4,28,5,29'
  physicaldevmappings: 'sriov1:ens1f1'
  pcipassthrough:
    - devname: ens1f1
      network: 'sriov1'
      trusted: true

# CephStorage default properties
CephStorageProperties:
  devices: ['/dev/sdb']

# Octavia parameters
DeployOctavia: False

# Subscription manager parameters
RegisterNodes: False

# vms is a list to define the virtual machines to be created. The role defines a minimum of one undercloud, one controller node and one compute node
vms:
  - name: undercloud
    title: 'RHOSPVirtLab Undercloud'
    profile: 'undercloud'
    memory: 6291456
    vcpus: 2
    bmcport: 6230
    mac: '0c:1f:0d:10:00'
    disk_size: 107374182400
    backing_store: "{{ RHOSP_version_supported[RHOSP_version].rhel_image.name }}"
    cdrom: 'undercloud-init.iso'
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_management: '192.168.250.10'
  - name: vcontroller0
    title: 'RHOSPVirtLab Virtual Controller 0'
    profile: 'vcontroller'
    memory: 8388608
    vcpus: 2
    bmcport: 6231
    mac: '0c:1f:0d:11:00'
    disk_size: 53687091200
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_external: ''
  - name: vcompute0
    title: 'RHOSPVirtLab Virtual Compute 0'
    profile: 'vcompute'
    memory: 6291456
    vcpus: 4
    bmcport: 6234
    mac: '0c:1f:0d:12:00'
    disk_size: 53687091200
    data_disk_size: 0
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_external: ''

# physical is a list to define the physical machines to be connected. The role doesn't define any by default
physical: []

# networks is a list to define the virtual networks to be created
networks:
  - name: RHOSPVirtLab_ctlplane
    bridge: br-ctlplane
    forward: false
    mac_suffix: '00'
    ipv4: false
  - name: RHOSPVirtLab_external
    bridge: br-external
    forward: nat
    mac_suffix: '05'
    ipv4:
      address: '10.0.0.1'
      netmask: '255.255.255.0'
      dhcp: false
  - name: RHOSPVirtLab_management
    bridge: br-management
    forward: nat
    mac_suffix: '0f'
    ipv4:
      address: '192.168.250.1'
      netmask: '255.255.255.0'
      dhcp:
        start: '192.168.250.100'
        end: '192.168.250.254'
        hosts: true
