---
# defaults file for RHOSP-undercloud

# RHOSP version
RHOSP_version: 17.1
RHOSP_release: latest

# Custom RHEL image: set URL to use a custom image. If it's a local file, use "file://<full_path>"
CustomRhelImage: "{{ RHOSP_version_supported[RHOSP_version].rhel_image.url }}"

# Cleaning and creating parameters
create: True

# overcloud parameters
overcloud_ip: 10.0.0.254
vncproxy: ''

# dns and ntp servers
dns_servers:
  - '8.8.8.8'
  - '8.8.4.4'
ntp_servers: 
  - '0.pool.ntp.org'
  - '1.pool.ntp.org'
  - '2.pool.ntp.org'
  - '3.pool.ntp.org'

# Default leaf configuration
DefaultLeaf0:
  name: overcloud
  hypervisor: localhost
  subnet:
    name: ctlplane-subnet
    cidr: 192.168.24.0/24
    dhcp_start: 192.168.24.5
    dhcp_end: 192.168.24.55
    inspection_iprange: 192.168.24.100,192.168.24.120
    gateway: 192.168.24.254
    masquerade: false
  networks:
    Tenant:
      prefix: '172.16.0'
      vlan: 10
      network: RHOSPVirtLab_ctlplane
    Storage:
      prefix: '172.16.1'
      vlan: 20
      network: RHOSPVirtLab_ctlplane
    InternalApi:
      prefix: '172.16.2'
      vlan: 30
      network: RHOSPVirtLab_ctlplane
    StorageMgmt:
      prefix: '172.16.3'
      vlan: 40
      network: RHOSPVirtLab_ctlplane
    External:
      prefix: '10.0.0'
      network: RHOSPVirtLab_external
    Management:
      prefix: '10.0.1'
      vlan: 60
      network: RHOSPVirtLab_ctlplane

# interfaces to use in each nic-config
interfaces:
  Controller:
    ControlPlane: nic1
    External: nic2
  Compute:
    ControlPlane: nic1
    External: nic2
  ComputeOvsDpdk:
    ControlPlane: nic1
    External: nic2
    DpdkBonds:
      - name: dpdkbond0
        ports:
          - name: dpdk0
            interface: nic3
            driver: vfio-pci
          - name: dpdk1
            interface: nic4
            driver: vfio-pci
  ComputeOvsDpdkSriov:
    ControlPlane: nic1
    External: nic2v0
    Sriov:
      - device: nic2
        numvfs: 8
    DpdkBonds:
      - name: dpdkbond0
        ports:
          - name: dpdk0
            interface: nic2v1
            driver: vfio-pci
          - name: dpdk1
            interface: nic2v2
            driver: vfio-pci
  ComputeSriov:
    ControlPlane: nic1
    External: nic2v0
    Sriov:
      - device: nic2
        numvfs: 8
  ComputeOvsHwOffload:
    ControlPlane: nic1
    External: nic2v0
    Sriov:
      - device: nic2
        numvfs: 8
  CephStorage:
    ControlPlane: nic1
    External: nic2
  ComputeHCI:
    ControlPlane: nic1
    External: nic2
  ComputeInstanceHA:
    ControlPlane: nic1
    External: nic2
  DistributedCompute:
    ControlPlane: nic1
    External: nic2
  DistributedComputeScaleOut:
    ControlPlane: nic1
    External: nic2
  DistributedComputeHCI:
    ControlPlane: nic1
    External: nic2
  DistributedComputeHCIScaleOut:
    ControlPlane: nic1
    External: nic2
  CephAll:
    ControlPlane: nic1
    External: nic2

# All computes default properties
BridgeMappings: 'datacentre:br-ex'
NetworkVlanRanges: 'datacentre:1:1000'

# ComputeSriov default properties
ComputeSriovProperties:
  isolcpus: '8-19'
  hugepagesz: '1GB'
  hugepages: 32
  kernelargs: 'iommu=pt intel_iommu=on'
  physicaldevmappings: 'datacentre:br-ex,sriov1:ens1f1'
  dedicatedcpus: '8-19'
  sharedcpus: '4-7'
  hostmemory: 8192
  pcipassthrough:
    - devname: ens1f1
      physical_network: 'sriov1'
      trusted: true

# ComputeOvsHwOffload default properties
ComputeOvsHwOffloadProperties:
  isolcpus: '8-19'
  hugepagesz: '1GB'
  hugepages: 32
  kernelargs: 'iommu=pt intel_iommu=on'
  physicaldevmappings: 'datacentre:br-ex,offload1:ens1f1'
  dedicatedcpus: '8-19'
  sharedcpus: '4-7'
  hostmemory: 8192
  pcipassthrough:
    - devname: ens1f1
      physical_network: 'sriov1'
      trusted: true

# ComputeOvsDpdk default properties
ComputeOvsDpdkProperties:
  isolcpus: '6-23,30-47'
  hugepagesz: '1GB'
  hugepages: 32
  kernelargs: 'iommu=pt intel_iommu=on'
  dedicatedcpus: '8-23,32-47'
  sharedcpus: '6-7,30-31'
  hostmemory: 8192
  socketmemory: '4096,4096'
  memorychannels: '4'
  ovsdpdkcorelist: '2,26,3,27'
  ovspmdcorelist: '4,28,5,29'

# ComputeOvsDpdkSriov default properties
ComputeOvsDpdkSriovProperties:
  isolcpus: '6-23,30-47'
  hugepagesz: '1GB'
  hugepages: 32
  kernelargs: 'iommu=pt intel_iommu=on'
  dedicatedcpus: '8-23,32-47'
  sharedcpus: '6-7,30-31'
  hostmemory: 8192
  socketmemory: '4096,4096'
  memorychannels: '4'
  ovsdpdkcorelist: '2,26,3,27'
  ovspmdcorelist: '4,28,5,29'
  physicaldevmappings: 'datacentre:br-ex,sriov1:ens1f1'
  pcipassthrough:
    - devname: ens1f1
      physical_network: 'sriov1'
      trusted: true

# CephStorage default properties
CephStorageProperties:
  devices: ['/dev/sdb']

# Octavia parameters
DeployOctavia: False

# Designate parameters
DeployDesignate: False

# FRR parameters
DeployFrr: False

# Subscription manager parameters
RegisterNodes: False

# Low Memory Usage parameters
LowMemUsage: True

# Enable fencing for controllers
ControllersFencing: True

# Neutron driver
NeutronDriver: ovn

# DCN leafs
DCNLeafs: []

# Disable telemetry
DisableTelemetry: True

# Telemetry parameters (Set DisableTelemetry to False to use)
Telemetry: False
#  MetricsConnectorHost: default-interconnect-5671-service-telemetry.apps.ocp-sno-for-stf.redhat.local
#  MetricsConnectorIPAddress: 10.8.223.249
#  Cloud: cloud1
#  Certificate: |
#    -----BEGIN CERTIFICATE-----
#    <snip>
#    -----END CERTIFICATE-----

# Default flavors size
DefaultFlavorsSize:
  - name: nano
    vcpus: 1
    ram: 128
    disk: 2
    ephemeral: 0
    swap: 0
  - name: micro
    vcpus: 1
    ram: 256
    disk: 5
    ephemeral: 0
    swap: 0
  - name: small
    vcpus: 1
    ram: 512
    disk: 10
    ephemeral: 0
    swap: 0
  - name: medium
    vcpus: 2
    ram: 1024
    disk: 10
    ephemeral: 0
    swap: 0
  - name: large
    vcpus: 2
    ram: 2048
    disk: 20
    ephemeral:
    swap: 0
  - name: xlarge
    vcpus: 4
    ram: 4096
    disk: 20
    ephemeral: 0
    swap: 0
  - name: 2xlarge
    vcpus: 8
    ram: 8192
    disk: 50
    ephemeral: 0
    swap: 0

# vms is a list to define the virtual machines to be created. The role defines a minimum of one undercloud, one controller node and one compute node
vms:
  - name: undercloud
    hypervisor: localhost
    title: 'RHOSPVirtLab Undercloud'
    profile: 'undercloud'
    memory: 6291456
    vcpus: 2
    bmcport: 6230
    mac: '0c:1f:0d:10:00'
    uefi: false
    disk_size: 107374182400
    backing_store: "{{ RHOSP_version_supported[RHOSP_version].rhel_image.name }}"
    cdrom: 'undercloud-init.iso'
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_management: '192.168.250.10'
  - name: controller0
    hypervisor: localhost
    title: 'RHOSPVirtLab Virtual Controller 0'
    profile: 'controller'
    memory: 8388608
    vcpus: 2
    bmcport: 6231
    mac: '0c:1f:0d:11:00'
    uefi: false
    disk_size: 53687091200
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_external: ''
  - name: compute0
    hypervisor: localhost
    title: 'RHOSPVirtLab Virtual Compute 0'
    profile: 'compute'
    memory: 6291456
    vcpus: 4
    bmcport: 6234
    mac: '0c:1f:0d:12:00'
    uefi: false
    disk_size: 53687091200
    data_disk_size: 0
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_external: ''

# physical is a list to define the physical machines to be connected. The role doesn't define any by default
physical: []

# networks is a list to define the virtual networks to be created
networks:
  - name: RHOSPVirtLab_ctlplane
    hypervisor: localhost
    bridge: br-ctlplane
    forward: bridge
    mac_suffix: '00'
    ipv4:
      address: '192.168.24.254'
      netmask: '255.255.255.0'
      dhcp: false
  - name: RHOSPVirtLab_external
    hypervisor: localhost
    bridge: br-external
    forward: bridge
    mac_suffix: '01'
    ipv4:
      address: '10.0.0.1'
      netmask: '255.255.255.0'
      dhcp: false
  - name: RHOSPVirtLab_management
    hypervisor: localhost
    bridge: br-management
    forward: nat
    mac_suffix: '02'
    ipv4:
      address: '192.168.250.1'
      netmask: '255.255.255.0'
      dhcp:
        start: '192.168.250.100'
        end: '192.168.250.254'
        hosts: true