---
# defaults file for RHOSP-undercloud

# RHOSP version
RHOSP_version: 16.2

# overcloud parameters
overcloud_ip: 10.0.0.254

# dns and ntp servers
dns_servers:
  - '8.8.8.8'
  - '8.8.4.4'
ntp_servers: 
  - '0.pool.ntp.org'
  - '1.pool.ntp.org'
  - '2.pool.ntp.org'
  - '3.pool.ntp.org'

# vlans to use in the network-data
network_data_vlans:
  External: 10
  InternalApi: 20
  Storage: 30
  StorageMgmt: 40
  Tenant: 50
  Management: 60

# interfaces to use in each nic-config
interfaces:
  controller:
    ControlPlane: nic1
    Vlans: nic2
    External: nic3
  compute:
    ControlPlane: nic1
    Vlans: nic2
    External: nic3
  computesriov:
    ControlPlane: nic1
    Vlans: nic2
    Provider: nic3

# ComputeSriov default properties
ComputeSriovProperties:
  isolcpus: '8-19'
  hugepagesz: '1GB'
  hugepages: 32
  kernelargs: 'iommu=pt intel_iommu=on'
  devmappings: 'sriov1:nic4,sriov2:nic5'
  sharedcpus: '4-7'
  hostmemory: 8192
  pcipassthrough:
    - vendor_id: 8086
      product_id: 1528
      address: '0000:85:00.0'
      network: 'sriov1'
    - vendor_id: 8086
      product_id: 1528
      address: '0000:85:00.1'
      network: 'sriov1'

# vms is a list to define the virtual machines to be created. The role defines a minimum of one undercloud, one controller node and one compute node
vms:
  - name: undercloud
    title: 'RHOSPVirtLab Undercloud'
    profile: 'undercloud'
    memory: 6291456
    vcpus: 2
    bmcport: 6230
    mac: '0c:1f:0d:10:00'
    disk_size: 107374182400
    backing_store: "{{ RHOSP_version_supported[RHOSP_version].rhel_image.name }}"
    cdrom: 'undercloud-init.iso'
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_management: '192.168.250.10'
  - name: controller0
    title: 'RHOSPVirtLab Controller 0'
    profile: 'control'
    memory: 8388608
    vcpus: 2
    bmcport: 6231
    mac: '0c:1f:0d:11:00'
    disk_size: 53687091200
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_vlans: ''
      RHOSPVirtLab_external: ''
  - name: compute0
    title: 'RHOSPVirtLab Compute 0'
    profile: 'compute'
    memory: 6291456
    vcpus: 4
    bmcport: 6234
    mac: '0c:1f:0d:12:00'
    disk_size: 53687091200
    backing_store: ''
    cdrom: ''
    nics:
      RHOSPVirtLab_ctlplane: ''
      RHOSPVirtLab_vlans: ''
      RHOSPVirtLab_external: ''

# physical is a list to define the physical machines to be connected. The role doesn't define any by default
physical:

# networks is a list to define the virtual networks to be created
networks:
  - name: RHOSPVirtLab_ctlplane
    bridge: br-ctlplane
    forward: false
    mac_suffix: '00'
    ipv4: false
    hypervisor_if: eno2
  - name: RHOSPVirtLab_vlans
    bridge: br-vlans
    forward: false
    mac_suffix: '01'
    ipv4: false
    hypervisor_if: eno3
  - name: RHOSPVirtLab_external
    bridge: br-external
    forward: route
    mac_suffix: '05'
    ipv4:
      address: '10.0.0.1'
      netmask: '255.255.255.0'
      dhcp: false
  - name: RHOSPVirtLab_management
    bridge: br-management
    forward: nat
    mac_suffix: '0f'
    ipv4:
      address: '192.168.250.1'
      netmask: '255.255.255.0'
      dhcp:
        start: '192.168.250.100'
        end: '192.168.250.254'
        hosts: true
